stages:
  - verify
  - build
  - test
  - scan
  - deploy
verify:
  stage: verify
  image: alpine:3.20
  script:
    - apk add --no-cache coreutils
    - sha256sum -c checksums.sha256 || exit 1
build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t my-envoy-image:latest .
  artifacts:
    paths:
      - my-envoy-image.tar
test:
  stage: test
  image: my-envoy-image:latest
  script:
    - /usr/local/bin/ebpf_tests
    - apk add --no-cache curl
    - curl -f http://localhost:10000 || exit 1
scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy image my-envoy-image:latest
deploy:
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push my-envoy-image:latest
  only:
    - main
